# Import Library 

In [1]:
import pickle
import pandas as pd
import numpy as np

# Load Model

In [2]:
# meload model
with open('model_scaler_cluster.pkl', 'rb') as file_1:
  model_scaler = pickle.load(file_1)

with open('model_kmeans.pkl', 'rb') as file_2:
  model_kmeans = pickle.load(file_2)

with open('model_pca.pkl', 'rb') as file_3:
  model_pca = pickle.load(file_3)

# New Data Random

In [3]:
# membuat kolom dengan value acak hingga 100 row
np.random.seed(0)
BALANCE = np.random.uniform(0,18495,100)
BALANCE_FREQUENCY = np.random.uniform(0,1,100)
PURCHASES = np.random.uniform(0,41050,100)
ONEOFF_PURCHASES = np.random.uniform(0,40624,100)
INSTALLMENTS_PURCHASES = np.random.uniform(0,14686,100)
CASH_ADVANCE = np.random.uniform(0,47137,100)
PURCHASES_FREQUENCY = np.random.uniform(0,1,100)
ONEOFF_PURCHASES_FREQUENCY = np.random.uniform(0,1,100)
PURCHASES_INSTALLMENTS_FREQUENCY = np.random.uniform(0,1,100)
CASH_ADVANCE_FREQUENCY = np.random.uniform(0,1.5,100)
CASH_ADVANCE_TRX = np.random.uniform(0,123,100)
PURCHASES_TRX = np.random.uniform(0,347,100)
CREDIT_LIMIT= np.random.uniform(50,30000,100)
PAYMENTS = np.random.uniform(0.049513,50721,100)
MINIMUM_PAYMENTS = np.random.uniform(0.019163,76406,100)
PRC_FULL_PAYMENT = np.random.uniform(0,1,100)
TENURE = np.random.choice(['6','7','8','9','10','11','12'],100)

In [4]:
# membuat nama kolom dalam bentuk dataFrame dengan data yang sudah dibuat secara acak
Inference_df = pd.DataFrame({
    'bal' : BALANCE,
    'bf': BALANCE_FREQUENCY,
    'pur': PURCHASES,
    'op': ONEOFF_PURCHASES,
    'ip' : INSTALLMENTS_PURCHASES,
    'ca': CASH_ADVANCE,
    'pf': PURCHASES_FREQUENCY,
    'opf': ONEOFF_PURCHASES_FREQUENCY,
    'pif' : PURCHASES_INSTALLMENTS_FREQUENCY,
    'caf': CASH_ADVANCE_FREQUENCY,
    'cat': CASH_ADVANCE_TRX,
    'pt': PURCHASES_TRX,
    'cal': CREDIT_LIMIT,
    'pay': PAYMENTS,
    'mp': MINIMUM_PAYMENTS,
    'pfp': PRC_FULL_PAYMENT,
    'ten': TENURE,

})

Inference_df

bal        bf           pur            op            ip  \
0   10150.305755  0.677817  12799.220956  36827.910600   5892.897029   
1   13227.427331  0.270008  28584.900216  31444.898844  13647.573755   
2   11148.108640  0.735194  15506.713003  13533.688656   1462.944865   
3   10077.614470  0.962189   7372.730964   3294.662867  13882.698321   
4    7835.495514  0.248753   1013.061800  16543.765348  12769.308560   
..           ...       ...           ...           ...           ...   
95   3388.124240  0.490459   9208.214039  38957.714093   3989.492545   
96  10847.556729  0.227415   4016.516088  14436.504100   6688.652779   
97    371.889067  0.254356  35392.961790  14490.860716   5899.564981   
98  15331.245840  0.058029  39938.345024    663.329093   3648.200148   
99     86.842832  0.434417  39442.262713   7524.877980   7429.153713   

              ca        pf       opf       pif       caf         cat  \
0   14630.420994  0.174658  0.373216  0.039993  1.216258   72.924273   
1   17583.744379  0.327988  0.222864  0.639705  0.522288    1.237835   
2   24745.531737  0.680349  0.080532  0.408303  0.317182   58.526622   
3   35380.797596  0.063208  0.085311  0.377407  0.089075   87.178758   
4   15720.541415  0.607249  0.221396  0.809365  1.314040    5.408978   
..           ...       ...       ...       ...       ...         ...   
95  47040.946641  0.365100  0.932561  0.498180  0.146515   93.355100   
96  17072.505671  0.190567  0.391797  0.866789  0.772383    2.098440   
97  22184.979519  0.019123  0.242179  0.627735  1.407618  118.947755   
98  17829.342810  0.518150  0.250398  0.401428  0.342970   75.652137   
99  46171.960868  0.842777  0.483394  0.416692  1.015712   67.950004   

            pt           cal           pay            mp       pfp ten  
0   102.694592   9290.412389  43980.923244  23960.217434  0.446793  10  
1   322.464210  28268.432335  14925.509054  27929.387141  0.836990  12  
2    92.269253  26653.537964  22081.591123  15378.003811  0.221824   6  
3   287.366875  25816.304816  40346.360622  37221.049613  0.493945   7  
4   341.832712  19607.342840  34363.917292  75670.097487  0.929619   9  
..         ...           ...           ...           ...       ...  ..  
95  194.476354  24939.381864  31453.423597   2324.786911  0.748606  12  
96  231.871726  19833.058505  31320.097852  14793.996579  0.452654   6  
97   99.490689   4613.316285  49979.386897   8576.589946  0.713718   8  
98    6.753476  29882.334567  45003.894295   3236.885733  0.915408  11  
99  138.530167   3051.991451  38805.124523  17400.793136  0.146584   7  

[100 rows x 17 columns]

### Scaling New Data Random with Model

In [5]:
# scaling model yang sudah dibuat lalu di fit dengan data baru
Inference_scaler = model_scaler.fit_transform(Inference_df)
Inference_scaler

array([[0.55314628, 0.67478496, 0.30555561, ..., 0.30285894, 0.43633677,
        0.66666667],
       [0.72228273, 0.2616607 , 0.6991149 , ..., 0.35577196, 0.83497094,
        1.        ],
       [0.60799131, 0.73291035, 0.37305721, ..., 0.18844941, 0.20650304,
        0.        ],
       ...,
       [0.01566779, 0.24580519, 0.8688495 , ..., 0.09777973, 0.70903284,
        0.33333333],
       [0.83792079, 0.04691878, 0.98217233, ..., 0.02659611, 0.91508381,
        0.83333333],
       [0.        , 0.42821238, 0.96980429, ..., 0.21541522, 0.12963584,
        0.16666667]])

### Dimentional Reduction New Data Random with model

In [6]:
# reduksi dimensi dari model yang sudah di scale
Inference_pca = model_pca.fit_transform(Inference_scaler)
Inference_pca

array([[ 5.04603027e-01,  1.88548825e-01,  2.90808262e-01,
        -5.57814490e-02, -1.05245262e-01,  3.54458394e-02,
        -1.19159926e-01, -6.88279855e-02,  5.62669645e-01,
        -4.60401246e-02],
       [ 4.43615720e-01, -4.04315209e-01, -6.94973050e-01,
         1.28226258e-02, -6.18718166e-01, -2.26047442e-01,
         2.62053123e-01,  7.42413157e-02, -3.38629029e-01,
        -1.63719029e-01],
       [-3.44593830e-01,  6.22899855e-01, -3.20365648e-01,
         2.63571810e-01,  1.37937245e-01, -1.46117489e-01,
        -4.73994868e-02, -9.03443480e-02,  4.81826813e-01,
         6.98188370e-02],
       [-7.35388008e-01,  2.64725862e-01, -1.83897364e-01,
         3.56594279e-02, -2.20613479e-01, -5.33767035e-01,
         4.65754829e-01, -3.48347929e-01,  1.70461746e-01,
        -2.83097358e-01],
       [-1.37749969e-01, -3.75002584e-01,  4.80657487e-02,
        -4.73401477e-01, -8.34026124e-01, -3.11794450e-01,
         1.98408333e-02,  3.19181193e-01, -2.51928026e-01,
         2.

### Predict New Data Random with model KMeans

In [7]:
# memprediksi data baru dengan model yang sudah dibuat
Inference_cluster = model_kmeans.predict(Inference_pca)
Inference_cluster

array([2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0])

### Predict Result

In [8]:
# membuat data frame hasil prediksi
Inference_cluster_df = pd.DataFrame(Inference_cluster, columns=['Clustering'])
Inference_cluster_df

Clustering
0            2
1            1
2            0
3            0
4            0
..         ...
95           1
96           0
97           2
98           1
99           0

[100 rows x 1 columns]

In [9]:
# menggabungkan data baru dan hasil prediksi clustering
Inference_table = pd.concat([Inference_df, Inference_cluster_df], axis=1)
Inference_table

bal        bf           pur            op            ip  \
0   10150.305755  0.677817  12799.220956  36827.910600   5892.897029   
1   13227.427331  0.270008  28584.900216  31444.898844  13647.573755   
2   11148.108640  0.735194  15506.713003  13533.688656   1462.944865   
3   10077.614470  0.962189   7372.730964   3294.662867  13882.698321   
4    7835.495514  0.248753   1013.061800  16543.765348  12769.308560   
..           ...       ...           ...           ...           ...   
95   3388.124240  0.490459   9208.214039  38957.714093   3989.492545   
96  10847.556729  0.227415   4016.516088  14436.504100   6688.652779   
97    371.889067  0.254356  35392.961790  14490.860716   5899.564981   
98  15331.245840  0.058029  39938.345024    663.329093   3648.200148   
99     86.842832  0.434417  39442.262713   7524.877980   7429.153713   

              ca        pf       opf       pif       caf         cat  \
0   14630.420994  0.174658  0.373216  0.039993  1.216258   72.924273   
1   17583.744379  0.327988  0.222864  0.639705  0.522288    1.237835   
2   24745.531737  0.680349  0.080532  0.408303  0.317182   58.526622   
3   35380.797596  0.063208  0.085311  0.377407  0.089075   87.178758   
4   15720.541415  0.607249  0.221396  0.809365  1.314040    5.408978   
..           ...       ...       ...       ...       ...         ...   
95  47040.946641  0.365100  0.932561  0.498180  0.146515   93.355100   
96  17072.505671  0.190567  0.391797  0.866789  0.772383    2.098440   
97  22184.979519  0.019123  0.242179  0.627735  1.407618  118.947755   
98  17829.342810  0.518150  0.250398  0.401428  0.342970   75.652137   
99  46171.960868  0.842777  0.483394  0.416692  1.015712   67.950004   

            pt           cal           pay            mp       pfp ten  \
0   102.694592   9290.412389  43980.923244  23960.217434  0.446793  10   
1   322.464210  28268.432335  14925.509054  27929.387141  0.836990  12   
2    92.269253  26653.537964  22081.591123  15378.003811  0.221824   6   
3   287.366875  25816.304816  40346.360622  37221.049613  0.493945   7   
4   341.832712  19607.342840  34363.917292  75670.097487  0.929619   9   
..         ...           ...           ...           ...       ...  ..   
95  194.476354  24939.381864  31453.423597   2324.786911  0.748606  12   
96  231.871726  19833.058505  31320.097852  14793.996579  0.452654   6   
97   99.490689   4613.316285  49979.386897   8576.589946  0.713718   8   
98    6.753476  29882.334567  45003.894295   3236.885733  0.915408  11   
99  138.530167   3051.991451  38805.124523  17400.793136  0.146584   7   

    Clustering  
0            2  
1            1  
2            0  
3            0  
4            0  
..         ...  
95           1  
96           0  
97           2  
98           1  
99           0  

[100 rows x 18 columns]

# Kesimpulan

Dalam tahap ini, kita telah menggunakan algoritma K-means untuk mengelompokkan pengguna kartu kredit menjadi tiga kelompok berdasarkan karakteristik yang diukur dalam dataset. Proses ini berakhir setelah 17 iterasi, menunjukkan bahwa pusat-pusat kluster mendekati posisi yang optimal.

Nilai inertia sebesar 3624.8135746087473 menunjukkan bahwa variasi dalam masing-masing kelompok relatif rendah, menandakan bahwa kelompok-kelompok ini memiliki karakteristik yang sangat berbeda satu sama lain. Dengan kata lain, model K-means berhasil mengklasifikasikan pengguna kartu kredit menjadi 3 kelompok dengan karakteristik yang beragam.